name = "Obfacescator"
uuid = "563ea7ce-49b9-4182-b5ce-74f9cf17e2f8"
authors = ["lgflorentino <lgflorentino@lgflorentino.engineer>"]
version = "0.0.1"

[deps]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
Lindenmayer = "d9db2020-d13e-4bf8-b13e-b12a3214b5ef"
Mellan = "9395f11c-09ed-45be-886c-23f223b99ebb"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
